const sqlite3 = require('sqlite3').verbose();
const oracledb = require('oracledb');
const path = require('path');
require('dotenv').config();

// Enable auto-commit for oracledb operations
oracledb.autoCommit = true;
// Fetch LOBs as String directly
oracledb.fetchAsString = [oracledb.CLOB];

const sqliteDbPath = path.join(__dirname, '..', 'facebook.db');
const sqliteDb = new sqlite3.Database(sqliteDbPath);

const requiredEnvVars = ['ORACLE_USER', 'ORACLE_PASSWORD', 'ORACLE_CONNECT_STRING'];
const missingEnvVars = requiredEnvVars.filter(key => !process.env[key]);
if (missingEnvVars.length > 0) {
    console.error(`FATAL: Missing required Oracle env vars: ${missingEnvVars.join(', ')}`);
    process.exit(1);
}

const oracleConfig = {
    user: process.env.ORACLE_USER,
    password: process.env.ORACLE_PASSWORD,
    connectString: process.env.ORACLE_CONNECT_STRING
};

async function querySqlite(sql, params = []) {
    return new Promise((resolve, reject) => {
        sqliteDb.all(sql, params, (err, rows) => {
            if (err) reject(err);
            else resolve(rows);
        });
    });
}

async function dropTablesIfExist(connection) {
    const tables = [
        'messages', 'tags', 'notifications', 'friendships',
        'comments', 'interactions', 'posts', 'otp_attempts',
        'email_verifications', 'password_resets', 'users', 'bait_patterns'
    ];

    for (const table of tables) {
        try {
            await connection.execute(`DROP TABLE ${table} CASCADE CONSTRAINTS`);
            console.log(`[Oracle Setup] Dropped table ${table}`);
        } catch (err) {
            // Ignore ORA-00942 (table does not exist)
        }
    }
}

async function createOracleTables(connection) {
    console.log("[Oracle Setup] Creating tables in Oracle Database XE...");

    await connection.execute(`
        CREATE TABLE users (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            username VARCHAR2(255) UNIQUE NOT NULL,
            password_hash VARCHAR2(255) NOT NULL,
            profile_picture VARCHAR2(2000),
            bio VARCHAR2(2000) DEFAULT '',
            cover_photo VARCHAR2(2000) DEFAULT '',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            two_factor_secret VARCHAR2(255),
            two_factor_enabled NUMBER(1) DEFAULT 0,
            email VARCHAR2(500),
            email_verified NUMBER(1) DEFAULT 0,
            token_version NUMBER(10) DEFAULT 1,
            live_typing_enabled NUMBER(1) DEFAULT 0
        )
    `);

    await connection.execute(`
        CREATE UNIQUE INDEX idx_users_email ON users(
            CASE WHEN email IS NOT NULL AND email != '' THEN email ELSE NULL END
        )
    `);

    await connection.execute(`
        CREATE TABLE password_resets (
            token_hash VARCHAR2(500) PRIMARY KEY,
            user_id NUMBER NOT NULL,
            expires_at NUMBER NOT NULL,
            used NUMBER(1) DEFAULT 0,
            ip_address VARCHAR2(255),
            user_agent VARCHAR2(2000),
            created_at NUMBER
        )
    `);

    await connection.execute(`
        CREATE TABLE email_verifications (
            token_hash VARCHAR2(500) PRIMARY KEY,
            user_id NUMBER NOT NULL,
            email VARCHAR2(500) NOT NULL,
            expires_at NUMBER NOT NULL,
            used NUMBER(1) DEFAULT 0,
            created_at NUMBER
        )
    `);

    await connection.execute(`
        CREATE TABLE otp_attempts (
            key VARCHAR2(2000) PRIMARY KEY,
            attempts NUMBER DEFAULT 1,
            first_attempt NUMBER
        )
    `);

    await connection.execute(`
        CREATE TABLE posts (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            user_id NUMBER NOT NULL,
            content CLOB,
            image_url VARCHAR2(2000),
            bait_score NUMBER DEFAULT 0,
            bait_translation CLOB,
            bait_roasts CLOB,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    `);
    await connection.execute(`CREATE INDEX idx_posts_user_id ON posts(user_id)`);

    await connection.execute(`
        CREATE TABLE interactions (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            post_id NUMBER NOT NULL,
            user_id NUMBER NOT NULL,
            type VARCHAR2(50) NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT unq_post_user_type UNIQUE(post_id, user_id, type)
        )
    `);
    await connection.execute(`CREATE INDEX idx_interactions_post_id ON interactions(post_id)`);

    await connection.execute(`
        CREATE TABLE comments (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            post_id NUMBER NOT NULL,
            user_id NUMBER NOT NULL,
            content CLOB NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    `);

    await connection.execute(`
        CREATE TABLE friendships (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            requester_id NUMBER NOT NULL,
            addressee_id NUMBER NOT NULL,
            status VARCHAR2(50) DEFAULT 'pending',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT unq_friendship UNIQUE(requester_id, addressee_id)
        )
    `);

    await connection.execute(`
        CREATE TABLE notifications (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            user_id NUMBER NOT NULL,
            actor_id NUMBER NOT NULL,
            type VARCHAR2(50) NOT NULL,
            target_id NUMBER,
            is_read NUMBER(1) DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    `);

    await connection.execute(`
        CREATE TABLE tags (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            post_id NUMBER NOT NULL,
            tagged_user_id NUMBER NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    `);

    await connection.execute(`
        CREATE TABLE messages (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            sender_id NUMBER NOT NULL,
            receiver_id NUMBER NOT NULL,
            content CLOB NOT NULL,
            is_read NUMBER(1) DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    `);

    await connection.execute(`
        CREATE TABLE bait_patterns (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            regex_pattern CLOB NOT NULL,
            flags VARCHAR2(50) DEFAULT '',
            label VARCHAR2(1000) NOT NULL,
            roast CLOB NOT NULL
        )
    `);

    console.log("[Oracle Setup] Successfully created all tables in Oracle XE.");
}

function parseTimestamp(val) {
    if (!val) return new Date();
    if (typeof val === 'number') return new Date(val);
    const d = new Date(val);
    return isNaN(d.getTime()) ? new Date() : d;
}

async function migrateData(connection) {
    console.log("\n[ETL Migration] Migrating data from SQLite to Oracle XE...");

    // 1. Users
    const users = await querySqlite("SELECT * FROM users");
    console.log(`[ETL] Users count: ${users.length}`);
    const validUserIds = new Set(users.map(u => u.id));

    for (const u of users) {
        await connection.execute(`
            INSERT INTO users (id, username, password_hash, profile_picture, bio, cover_photo, created_at, two_factor_secret, two_factor_enabled, email, email_verified, token_version, live_typing_enabled)
            VALUES (:id, :username, :password_hash, :profile_picture, :bio, :cover_photo, :created_at, :two_factor_secret, :two_factor_enabled, :email, :email_verified, :token_version, :live_typing_enabled)
        `, {
            id: u.id,
            username: u.username,
            password_hash: u.password_hash,
            profile_picture: u.profile_picture || null,
            bio: u.bio || '',
            cover_photo: u.cover_photo || '',
            created_at: parseTimestamp(u.created_at),
            two_factor_secret: u.two_factor_secret || null,
            two_factor_enabled: u.two_factor_enabled || 0,
            email: u.email || null,
            email_verified: u.email_verified || 0,
            token_version: u.token_version || 1,
            live_typing_enabled: u.live_typing_enabled || 0
        });
    }

    // 2. Password Resets
    const resets = await querySqlite("SELECT * FROM password_resets");
    console.log(`[ETL] Password Resets count: ${resets.length}`);
    for (const r of resets) {
        if (!validUserIds.has(r.user_id)) continue;
        await connection.execute(`
            INSERT INTO password_resets (token_hash, user_id, expires_at, used, ip_address, user_agent, created_at)
            VALUES (:token_hash, :user_id, :expires_at, :used, :ip_address, :user_agent, :created_at)
        `, {
            token_hash: r.token_hash,
            user_id: r.user_id,
            expires_at: r.expires_at,
            used: r.used || 0,
            ip_address: r.ip_address || null,
            user_agent: r.user_agent || null,
            created_at: r.created_at || null
        });
    }

    // 3. Email Verifications
    const evs = await querySqlite("SELECT * FROM email_verifications");
    console.log(`[ETL] Email Verifications count: ${evs.length}`);
    for (const e of evs) {
        if (!validUserIds.has(e.user_id)) continue;
        await connection.execute(`
            INSERT INTO email_verifications (token_hash, user_id, email, expires_at, used, created_at)
            VALUES (:token_hash, :user_id, :email, :expires_at, :used, :created_at)
        `, {
            token_hash: e.token_hash,
            user_id: e.user_id,
            email: e.email,
            expires_at: e.expires_at,
            used: e.used || 0,
            created_at: e.created_at || null
        });
    }

    // 4. OTP Attempts
    const otps = await querySqlite("SELECT * FROM otp_attempts");
    console.log(`[ETL] OTP Attempts count: ${otps.length}`);
    for (const o of otps) {
        await connection.execute(`
            INSERT INTO otp_attempts (key, attempts, first_attempt)
            VALUES (:key, :attempts, :first_attempt)
        `, {
            key: o.key,
            attempts: o.attempts || 1,
            first_attempt: o.first_attempt || null
        });
    }

    // 5. Posts
    const posts = await querySqlite("SELECT * FROM posts");
    console.log(`[ETL] Posts count: ${posts.length}`);
    const validPostIds = new Set();
    for (const p of posts) {
        if (!validUserIds.has(p.user_id)) continue;
        validPostIds.add(p.id);
        await connection.execute(`
            INSERT INTO posts (id, user_id, content, image_url, bait_score, bait_translation, bait_roasts, created_at, updated_at)
            VALUES (:id, :user_id, :content, :image_url, :bait_score, :bait_translation, :bait_roasts, :created_at, :updated_at)
        `, {
            id: p.id,
            user_id: p.user_id,
            content: p.content || '',
            image_url: p.image_url || null,
            bait_score: p.bait_score || 0,
            bait_translation: p.bait_translation || '',
            bait_roasts: p.bait_roasts || '',
            created_at: parseTimestamp(p.created_at),
            updated_at: parseTimestamp(p.updated_at)
        });
    }

    // 6. Interactions
    const interactions = await querySqlite("SELECT * FROM interactions");
    console.log(`[ETL] Interactions count: ${interactions.length}`);
    for (const i of interactions) {
        if (!validUserIds.has(i.user_id) || !validPostIds.has(i.post_id)) continue;
        await connection.execute(`
            INSERT INTO interactions (id, post_id, user_id, type, created_at)
            VALUES (:id, :post_id, :user_id, :type, :created_at)
        `, {
            id: i.id,
            post_id: i.post_id,
            user_id: i.user_id,
            type: i.type,
            created_at: parseTimestamp(i.created_at)
        });
    }

    // 7. Comments
    const comments = await querySqlite("SELECT * FROM comments");
    console.log(`[ETL] Comments count: ${comments.length}`);
    for (const c of comments) {
        if (!validUserIds.has(c.user_id) || !validPostIds.has(c.post_id)) continue;
        await connection.execute(`
            INSERT INTO comments (id, post_id, user_id, content, created_at, updated_at)
            VALUES (:id, :post_id, :user_id, :content, :created_at, :updated_at)
        `, {
            id: c.id,
            post_id: c.post_id,
            user_id: c.user_id,
            content: c.content,
            created_at: parseTimestamp(c.created_at),
            updated_at: parseTimestamp(c.updated_at)
        });
    }

    // 8. Friendships
    const friendships = await querySqlite("SELECT * FROM friendships");
    console.log(`[ETL] Friendships count: ${friendships.length}`);
    for (const f of friendships) {
        if (!validUserIds.has(f.requester_id) || !validUserIds.has(f.addressee_id)) continue;
        await connection.execute(`
            INSERT INTO friendships (id, requester_id, addressee_id, status, created_at)
            VALUES (:id, :requester_id, :addressee_id, :status, :created_at)
        `, {
            id: f.id,
            requester_id: f.requester_id,
            addressee_id: f.addressee_id,
            status: f.status || 'pending',
            created_at: parseTimestamp(f.created_at)
        });
    }

    // 9. Notifications
    const notifications = await querySqlite("SELECT * FROM notifications");
    console.log(`[ETL] Notifications count: ${notifications.length}`);
    for (const n of notifications) {
        if (!validUserIds.has(n.user_id) || !validUserIds.has(n.actor_id)) continue;
        await connection.execute(`
            INSERT INTO notifications (id, user_id, actor_id, type, target_id, is_read, created_at)
            VALUES (:id, :user_id, :actor_id, :type, :target_id, :is_read, :created_at)
        `, {
            id: n.id,
            user_id: n.user_id,
            actor_id: n.actor_id,
            type: n.type,
            target_id: n.target_id || null,
            is_read: n.is_read || 0,
            created_at: parseTimestamp(n.created_at)
        });
    }

    // 10. Tags
    const tags = await querySqlite("SELECT * FROM tags");
    console.log(`[ETL] Tags count: ${tags.length}`);
    for (const t of tags) {
        if (!validPostIds.has(t.post_id) || !validUserIds.has(t.tagged_user_id)) continue;
        await connection.execute(`
            INSERT INTO tags (id, post_id, tagged_user_id, created_at)
            VALUES (:id, :post_id, :tagged_user_id, :created_at)
        `, {
            id: t.id,
            post_id: t.post_id,
            tagged_user_id: t.tagged_user_id,
            created_at: parseTimestamp(t.created_at)
        });
    }

    // 11. Messages
    const messages = await querySqlite("SELECT * FROM messages");
    console.log(`[ETL] Messages count: ${messages.length}`);
    for (const m of messages) {
        if (!validUserIds.has(m.sender_id) || !validUserIds.has(m.receiver_id)) continue;
        await connection.execute(`
            INSERT INTO messages (id, sender_id, receiver_id, content, is_read, created_at)
            VALUES (:id, :sender_id, :receiver_id, :content, :is_read, :created_at)
        `, {
            id: m.id,
            sender_id: m.sender_id,
            receiver_id: m.receiver_id,
            content: m.content,
            is_read: m.is_read || 0,
            created_at: parseTimestamp(m.created_at)
        });
    }

    // 12. Bait Patterns
    const baitPatterns = await querySqlite("SELECT * FROM bait_patterns");
    console.log(`[ETL] Bait Patterns count: ${baitPatterns.length}`);
    if (baitPatterns.length > 0) {
        const batchSize = 500;
        for (let i = 0; i < baitPatterns.length; i += batchSize) {
            const chunk = baitPatterns.slice(i, i + batchSize);
            const binds = chunk.map(bp => ({
                id: bp.id,
                regex_pattern: bp.regex_pattern,
                flags: bp.flags || '',
                label: bp.label,
                roast: bp.roast
            }));

            await connection.executeMany(`
                INSERT INTO bait_patterns (id, regex_pattern, flags, label, roast)
                VALUES (:id, :regex_pattern, :flags, :label, :roast)
            `, binds);
        }
    }

    console.log("\n[ETL Migration] Data insertion completed successfully.");
}

async function addForeignKeys(connection) {
    console.log("\n[Oracle Setup] Adding Foreign Key constraints...");
    const constraints = [
        `ALTER TABLE posts ADD CONSTRAINT fk_posts_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE`,
        `ALTER TABLE interactions ADD CONSTRAINT fk_inter_post FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE`,
        `ALTER TABLE interactions ADD CONSTRAINT fk_inter_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE`,
        `ALTER TABLE comments ADD CONSTRAINT fk_comments_post FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE`,
        `ALTER TABLE comments ADD CONSTRAINT fk_comments_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE`,
        `ALTER TABLE friendships ADD CONSTRAINT fk_friends_req FOREIGN KEY(requester_id) REFERENCES users(id) ON DELETE CASCADE`,
        `ALTER TABLE friendships ADD CONSTRAINT fk_friends_add FOREIGN KEY(addressee_id) REFERENCES users(id) ON DELETE CASCADE`,
        `ALTER TABLE notifications ADD CONSTRAINT fk_notif_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE`,
        `ALTER TABLE notifications ADD CONSTRAINT fk_notif_actor FOREIGN KEY(actor_id) REFERENCES users(id) ON DELETE CASCADE`,
        `ALTER TABLE tags ADD CONSTRAINT fk_tags_post FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE`,
        `ALTER TABLE tags ADD CONSTRAINT fk_tags_user FOREIGN KEY(tagged_user_id) REFERENCES users(id) ON DELETE CASCADE`,
        `ALTER TABLE messages ADD CONSTRAINT fk_msg_sender FOREIGN KEY(sender_id) REFERENCES users(id) ON DELETE CASCADE`,
        `ALTER TABLE messages ADD CONSTRAINT fk_msg_receiver FOREIGN KEY(receiver_id) REFERENCES users(id) ON DELETE CASCADE`
    ];

    for (const sql of constraints) {
        try {
            await connection.execute(sql);
        } catch (err) {
            console.warn(`[Oracle Setup Warning] ${sql}: ${err.message}`);
        }
    }
}

async function reseedSequences(connection) {
    console.log("\n[Oracle Setup] Reseeding identity sequences to max(id) + 1...");
    const identityTables = [
        'users', 'posts', 'interactions', 'comments',
        'friendships', 'notifications', 'tags', 'messages', 'bait_patterns'
    ];

    for (const table of identityTables) {
        const res = await connection.execute(`SELECT NVL(MAX(id), 0) + 1 AS NEXT_ID FROM ${table}`);
        const nextId = res.rows[0][0];
        await connection.execute(`
            ALTER TABLE ${table} MODIFY id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH ${nextId})
        `);
        console.log(`[Oracle Setup] ${table} identity sequence reset to start with ${nextId}`);
    }
}

async function main() {
    let connection;
    try {
        console.log(`[Oracle Setup] Connecting to Oracle Database XE (${oracleConfig.connectString}) as user '${oracleConfig.user}'...`);
        connection = await oracledb.getConnection(oracleConfig);
        console.log("[Oracle Setup] Connected successfully.");

        await dropTablesIfExist(connection);
        await createOracleTables(connection);
        await migrateData(connection);
        await addForeignKeys(connection);
        await reseedSequences(connection);

        console.log("\n✅ [SUCCESS] Migration from SQLite to Oracle XE completed successfully!");
    } catch (err) {
        console.error("\n❌ [ERROR] Migration failed:", err);
    } finally {
        if (connection) {
            try {
                await connection.close();
            } catch (err) {
                console.error("Error closing connection:", err);
            }
        }
        sqliteDb.close();
    }
}

main();
